### ISSUE TITLE
Lesson 1 - Error interpreting standard preamble file `Fift.fif`: cannot locate file `Fift.fif`

### ISSUE THREAD

**Issue by jobman** [romanovichim/TonFunClessons_ru#1]
нахожусь в папке wallet
вызываю команду:
toncli deploy -n testnet

`INFO: 👻 Your smart contract project [D:\PyCharm\toncli\wallet] is now going to be deployed, get ready!
INFO: 🌈 Start building: 
INFO: 🌲 Func compiled
INFO: 🤗 Run tests on ['D:\\PyCharm\\toncli\\wallet\\fift\\data.fif']
[ 1][t 0][2022-05-10 08:54:59.6166034][fift-main.cpp:180]       Error interpreting standard preamble file `Fift.fif`: cannot locate file `Fift.fif`
Check that correct include path is set by -I or by FIFTPATH environment variable, or disable standard preamble by -n.
INFO: 🌲 Tests passed
INFO: 🥳 Start contract manipulation
[ 1][t 0][2022-05-10 08:54:59.6714437][fift-main.cpp:180]       Error interpreting standard preamble file `Fift.fif`: cannot locate file `Fift.fif`
Check that correct include path is set by -I or by FIFTPATH environment variable, or disable standard preamble by -n.
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\PyCharm\toncli\venv\Scripts\toncli.exe\__main__.py", line 7, in <module>
  File "D:\PyCharm\toncli\venv\lib\site-packages\toncli\main.py", line 424, in main
    deployer.publish(real_args[2:])
  File "D:\PyCharm\toncli\venv\lib\site-packages\toncli\modules\deploy_contract.py", line 86, in publish
    self.build(real_contracts)
  File "D:\PyCharm\toncli\venv\lib\site-packages\toncli\modules\abstract\deployer.py", line 107, in build
    data.append(contract_manipulation(os.path.abspath(contract.to_save_location),
  File "D:\PyCharm\toncli\venv\lib\site-packages\toncli\modules\utils\fift\commands.py", line 94, in contract_manipulation
    output = subprocess.check_output(command, cwd=getcwd() if not cwd else cwd)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['D:\\PyCharm\\toncli\\ton-win64-binaries\\fift.exe', '-I', 'C:\\Users\\user\\AppData\\Local\\toncli\\toncli\\fift-libs', '
-s', 'C:\\Users\\user\\AppData\\Local\\Temp\\tmpqgng6kvj.boc', '']' returned non-zero exit status 2.`

Не могу понять как починить и что я делаю не так, если не сложно помогите пожалуйста

**Comment by jobman** [comment]
Пересоздавал - то же самое
Напишу разработчикам toncli может быть действительно что то не так, у меня уже была проблема с mylocalTon, на моем процессоре не поддерживается инструкции AVX2, может быть тут тоже что то с этим связанно

**Comment by romanovichim** [comment]
Если они что-то толковое посоветуют, напиши пожалуйста это мне, я либо в
урок добавлю либо потом в раздел частые вопросы/проблемы

Вт, 10 мая 2022 г. в 17:39, jobman ***@***.***>:

**Comment by jobman** [comment]
Да, помогли:
https://github.com/disintar/toncli/issues/44

Для того что бы починить зашел в 
\ton_lesson1\venv\Lib\site-packages\toncli\lib\fift-libs
скопировал все содержимое в 
\ton_lesson1\wallet

INFO: 🙀 All contracts successfully deployed!

**Comment by romanovichim** [comment]
Супер, спасибо

Ср, 11 мая 2022 г. в 11:37, jobman ***@***.***>:
